import Map from '@/components/home/Map'
import Header from '@/layout/header'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Room Service</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<Header />

			<main className='h-[100vh] bg-yellow-200'>
				<Map />
			</main>
		</>
	)
}

export default Home
