import EndSection from "@/components/home/EndSection";
import FeatureScene from "@/components/home/FeatureScene";
import HeroScene from "@/components/home/HeroScene";
import LockedCard from "@/components/home/LockedCard";
import LockedStarts from "@/components/home/LockedStarts";
import RoomBanner from "@/components/home/RoomBanner";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Room Service</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <HeroScene />
        <RoomBanner className="bg-[#0A0517]" />
        <FeatureScene />
        <LockedStarts />
        <RoomBanner className="bg-[#FEFBF2]" />
        <LockedCard />
        <RoomBanner className="bg-[#FEFBF2]" />
        <EndSection />
      </main>
    </>
  );
};

export default Home;
