import EndSection from '@/components/home/EndSection'
import FeatureScene from '@/components/home/FeatureScene'
import HeroScene from '@/components/home/HeroScene'
import LockedCard from '@/components/home/LockedCard'
import LockedStarts from '@/components/home/LockedStarts'
import RoomBannerDark from '@/components/home/RoomBanner_dark'
import RoomBannerLight from '@/components/home/RoomBanner_light'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Room Service</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main>
				<HeroScene />
				<RoomBannerDark />
				<FeatureScene />
				<LockedStarts />
				<RoomBannerLight />
				<LockedCard />
				<RoomBannerLight />
				<EndSection />
			</main>
		</>
	)
}

export default Home
